spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    #hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/mgtop?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root 
    password: p@ssw0rd 
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 300 # jdbc connection pool , default 100
    max-wait: 15000
    test-on-borrow: true
    initial-size: 20
    test-while-idle: true
    time-between-eviction-runs-millis: 15000
    min-evictable-idle-time-millis: 18000
    validation-query: 'select 1'
  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://127.0.0.1:27017/db_mgtop
    #elasticsearch:
    #  cluster-name: logaa-elasticsearch
    #  cluster-nodes: 127.0.0.1:9300
    #  local: false
    #  repositories:
    #      enable: true
  redis:
    database: 1
    host: localhost
    password:
    port: 6379
    pool:
      max-idle: 50
      min-idle: 10
      max-active: 150
      max-wait: 1000
  thymeleaf.cache: false
  thymeleaf.mode: LEGACYHTML5
  profiles: local
server:
  #contextPath: /web
  port: 80

---
spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    #hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://192.169.235.181:33060/mgtop?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root 
    password: p@ssw0rd 
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 300 # jdbc connection pool , default 100
    max-wait: 15000
    test-on-borrow: true
    initial-size: 20
    test-while-idle: true
    time-between-eviction-runs-millis: 15000
    min-evictable-idle-time-millis: 18000
    validation-query: 'select 1'
  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://dbmgtop:p%40ssw0rd@192.169.235.181:27017/db_mgtop 
    #elasticsearch:
    #  cluster-name: logaa-elasticsearch
    #  cluster-nodes: 127.0.0.1:9300
    #  local: false
    #  repositories:
    #      enable: true
  redis:
    database: 1
    host: 192.169.235.181
    password: p@ssw0rd
    port: 63790
    pool:
      max-idle: 50
      min-idle: 10
      max-active: 150
      max-wait: 1000
  thymeleaf.cache: false
  thymeleaf.mode: LEGACYHTML5
  profiles: sit
server:
  #contextPath: /web
  port: 80
